### ISSUE TITLE
Conda install build error since latest anaconda3 image update

### ISSUE THREAD

**Issue by DeCato** [ContinuumIO/docker-images#136]
I wanted to rebuild an image based on anaconda3 I have used/tested for a few months, but all of the sudden the build fails.

The docker file was not changed, yet the build always failes on the 2nd conda install command, even if I switch the order of them (in this case the first conda install was for jupyter)

I get the following fatal error:

Step 18/22 : RUN conda install flask=0.12.2 -y
 ---> Running in e21496d929f1
Traceback (most recent call last):
  File "/opt/conda/bin/conda", line 7, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'

Any idea how to fix this?

**Comment by andreacassioli** [comment]
Same here using miniconda3 alpine.  The path seems not to contain the executables.

**Comment by soapy1** [comment]
You can add these 2 commands before you start running conda commands 

```
. /opt/conda/etc/profile.d/conda.sh && \
 conda activate base
```

this will activate conda and it should work fine

**Comment by DeCato** [comment]
@soapy1 
Thanks for the suggesttion, but this still gives the same error on the second conda command.

Step 17/23 : RUN        . /opt/conda/etc/profile.d/conda.sh &&          conda activate base
 ---> Running in b5cce255de57
Removing intermediate container b5cce255de57
 ---> ebe509a1dea9
Step 18/23 : RUN conda install jupyterlab -y
 ---> Running in 0995b5b8fef8
Solving environment: ...working... done
Step 19/23 : RUN conda install flask=0.12.2 -y
 ---> Running in 4d9310a15a42
Traceback (most recent call last):
  File "/opt/conda/bin/conda", line 7, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'

**Comment by hojo0590** [comment]
I'm using `continuumio/anaconda3:latest` in a gitlab-CI and I noticed a related behaviour.
Sometimes the first, sometimes the second conda statement (`conda activate`) in my script failed.
```console
conda: command not found
```
or
```console
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
```
Also calling the executable directly `/opt/conda/bin/conda` did not work.
Isn't the documentation of your docker containers claiming that conda will be on the user's path?
> The Anaconda distribution is installed into the /opt/conda folder and ensures that the default user has the conda command in their path.

Nevertheless the [answer](https://github.com/ContinuumIO/docker-images/issues/136#issuecomment-513834870) from @soapy1 has helped and the build is running now.

**Comment by andreacassioli** [comment]
I simply add `/opt/conda/bin/` and it works.

However it seems to me a bug that the path does not point to the conda tooling.

**Comment by playermanny2** [comment]
Receiving the same error as well, as of recently.

@andreacassioli  could you explain a bit more your solution?

**Comment by djwhiteastro** [comment]
I'm having similar issues. What I've noticed is that using the miniconda image pip/conda commands work fine within a Dockerfile, and it seems to be down to the $PATH variables in the containers:

Anaconda3:
Sending build context to Docker daemon  186.4kB
Step 1/2 : FROM continuumio/anaconda3
 ---> cd83b04b8169
Step 2/2 : RUN echo $PATH
 ---> Running in 6c8660edcb7f
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Miniconda3:
Sending build context to Docker daemon  186.4kB
Step 1/2 : FROM continuumio/miniconda3
 ---> 6b5cf97566c3
Step 2/2 : RUN echo $PATH
 ---> Running in f24aceeba1b7
/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by mingwandroid** [comment]
Please use conda as we advise. You must activate.

**Comment by hoto17296** [comment]
I resolved by using `bash -l` to load `~/.bashrc` to activate.

``` Dockerfile
FROM continuumio/anaconda3:2019.07

SHELL ["/bin/bash", "-l", "-c"]

RUN conda install -y ...

RUN pip install ...

RUN echo 'exec "$@"' > /entrypoint.sh
ENTRYPOINT ["/bin/bash", "-l", "/entrypoint.sh"]
```

**Comment by djwhiteastro** [comment]
> Please use conda as we advise. You must activate.

In my case, I couldn't activate conda because it doesn't appear on the path. This is an image issue.

**Comment by AmmarAkran** [comment]
Just update conda to compatible with python works for me in docker by:

'''
RUN conda update -n base conda
'''
before conda command

**Comment by zingi** [comment]
> > Please use conda as we advise. You must activate.
> 
> In my case, I couldn't activate conda because it doesn't appear on the path. This is an image issue.

For me I fixed it, like @djwhiteastro suggests, with setting a correct value to the PATH environment variable: **ENV PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin** before using the conda command.

(I am using this image: continuumio/miniconda3:4.7.12-alpine)

**Comment by divgo** [comment]
I had this same issue for the past few days, and just came across this issue today while researching. 

For me, I had the conda activate lines in my Dockerfile, and it was still throwing this error.

I added the following,
**cat ~/.bashrc**
and it seems to have corrected the issue, though I am not sure why this would have corrected the issue. 

```RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    cat ~/.bashrc```

**Comment by yiakwy** [comment]
I confirmed that " ENV PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin before using the conda command." is the real panacea.
